### ISSUE TITLE
 /content/UTKFace missing?

### ISSUE THREAD

**Issue by kajala** [emirhanai/Age-and-Sex-Prediction-from-Image---Convolutional-Neural-Network-with-Artificial-Intelligence#1]
The directory /content/UTKFace is missing? age_and_sex_prediction_from_image_convolutional_neural_network_with_artificial_intelligence.py starts by reading files from that directory, and it's not in the repository

**Comment by emirhanai** [comment]
Oh Hey Kajala!
This is dataset.
Dataset Link: https://www.kaggle.com/jangedoo/utkface-new
